spring:
  datasource:
    url: jdbc:mysql://47.94.92.122:3306/big_event?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: tang
    password: Tang29125.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


#?????????????????
mybatis:
  configuration:
    map-underscore-to-camel-case: true
